# Generated by Django 5.2.13 on 2026-04-16 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="portfolio_a_user_id_836f13_idx",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="start_date",
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "-created_at"], name="portfolio_a_user_id_71f356_idx"
            ),
        ),
    ]
